### PR TITLE
Ongoing work jk 07 24

### PR DESCRIPTION
**Pull request by jkingslake**
Add displacement calculations based on [George](glugeorge)'s work in his [fork](https://github.com/glugeorge/xapres_package). 
See the usingXApRES [NB](https://github.com/ldeo-glaciology/xapres/blob/ongoing-work-jk-07-24/notebooks/guides/usingXApRES.ipynb) for details on how to use and test the new functionality.  

This also adds two new unit tests. 

It also improves how bound methods are added to xarray.dataarrays - now this is done in a more easily extendible way upon loading the package, rather then when data is loaded.

### CODE REVIEW

**Review by glugeorge — COMMENTED** [review]
I think the changes to the displacement calculations look good. There seems to be a lot of zarr files being saved to git as well - do we want those included?

Also, I think a guide to calculating the profiles rather than having those readily included in the xarray could be useful, especially given the possibility of using a reduced chirp bandwidth with clipped data. I can try to add that in

**Comment by jkingslake** [comment]
Thanks @glugeorge. Good point, we dont need that zarr directory in there. I created it to save time loading profiles from the google bucket over-and-over again. It was only 32MB, so not an issue to keep in the repo if we find it useful in the future, but not necessary for now. I deleted them and modified the notebook that was loading them to instead load directly from the google bucket.

**Comment by jkingslake** [comment]
The computation of the profiles is a separate issue, but I definitely agree that we should add the ability to compute your own and include an explanation of the process in a notebook. 

see also #36

**Comment by jkingslake** [comment]
@glugeorge if you are happy with this PR can you approve it and then I will merge. Thanks again!

**Review by glugeorge — APPROVED** [review]
Looks good now!

**Pull request merged**
